[package]
name = "pulsepointer"
version = "0.1.0"
edition = "2021"
description = "PulsePointer: A Linux utility that visualizes audio output on your mouse cursor using X11 and PulseAudio."
authors = ["Simon"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/simonskrede/pulsepointer"
keywords = ["x11", "cursor", "audio", "visualization", "pulseaudio"]

[dependencies]
x11 = { version = "2.21", features = ["xfixes", "xcursor"] }
libpulse-binding = "2.28"
libpulse-simple-binding = "2.28"
ctrlc = "3.4"
bytemuck = { version = "1.19", features = ["extern_crate_std"] }
libc = "0.2"
clap = { version = "4.5.53", features = ["derive"] }
rustfft = "6.4.1"
